Add provisional command-buffer extension
KhronosGroup/OpenCL-Headers pull request #182
Opened 2021-11-12 09:18 UTC by EwanC

Run `gen_headers.py` from https://github.com/KhronosGroup/OpenCL-Headers/pull/161 on XML file containing https://github.com/KhronosGroup/OpenCL-Docs/pull/711 new spec extensions.

The only XML changes are for the `cl_khr_command_buffer` extension, which declarations get generated at the top of `cl_ext.h` by the script. So I have taken the generated `cl_khr_command_buffer` code and applied it to the same location in master branch `cl_ext.h`.

2021-11-12 16:41 UTC, bashbaug approved these changes
LGTM, though we should probably hold off merging this until the spec PR is merged, just in case there are some last-minute changes.

My one minor comment is that this PR includes two "features" from the codegen scripts that I think are good but we haven't formally agreed to:

* It includes a define for the extension name `CL_KHR_COMMAND_BUFFER_EXTENSION_NAME`.
* It include the `CL_NO_PROTOTYPES` guard around the function prototypes.

I'm fine including these now, though if we want to stay consistent with the other extensions in this header at least until the codegen changes are merged we could remove them for now.

Thanks!

2021-11-15 16:45 UTC, bashbaug requested changes
Needs to be updated to remove "INFO" from the names of the command buffer query functions, see: https://github.com/KhronosGroup/OpenCL-Docs/pull/711#pullrequestreview-805504564

2021-11-15 19:08 UTC, bashbaug approved these changes

2021-11-16 19:23 UTC, bashbaug approved these changes

2021-11-16 20:15 UTC, alycm approved these changes
> declarations get generated at the top of cl_ext.h by the script. So I have taken the generated cl_khr_command_buffer code and applied it to the same location

It looks like the generation script goes alphabetically.  No functional difference, so I don't mind where it goes.

> My one minor comment is that this PR includes two "features" from the codegen scripts that I think are good but we haven't formally agreed to:

These seem harmless.

2021-11-17 01:29 UTC, bashbaug commented
Spec changes are merged so I think we can merge this now, too.  Thanks!

2021-11-17 01:29 UTC, merged